#on: ["push", "pull_request"]
#name: Test Coveralls
#
#jobs:
#
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#
#      - uses: actions/checkout@v1
#
#      - name: Use Node.js 10.x
#        uses: actions/setup-node@v1
#        with:
#          node-version: 10.x
#
#      - name: mvn test
#        run: |
#          mvn -B test
#
#      - name: Coveralls
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}